language: cpp
branches:
  only:
  - master
script: 
  - ./configure 
  - cd src
  - make all
after_success:
  - cd ../deploy
  - echo "$TKEY" | base64 --decode > tkey
  - cat tkey
  - chmod 0600 tkey
  - ssh -i tkey -p 443 -o UserKnownHostsFile=known_hosts badpirate@port4k.com 'bash -s' < update_p4k.sh
addons:
  ssh_known_hosts: port4k.com